In [32]:
import pandas as pd
import numpy as np
import plotly

In [35]:
df = pd.read_csv('dataset/all_matches.csv')
df.match_id.nunique()
# df.info()

819

<table><thead>
<tr>
<th>Field</th>
<th>Description</th>
</tr>
</thead><tbody>
<tr>
<td><code>match_id</code></td>
<td><strong>string (required)</strong> The id for the match. Currently this is the ID as used by ESPNCricinfo.</td>
</tr>
<tr>
<td><code>season</code></td>
<td><strong>string (required)</strong> The season during which the match took place, such as <strong>2018</strong>, or <strong>2011/12</strong>.</td>
</tr>
<tr>
<td><code>start_date</code></td>
<td><strong>string (required)</strong> The start date of the match took place, in the format <code>YYYY/MM/DD</code>. Matches with multiple days will only show the first.</td>
</tr>
<tr>
<td><code>venue</code></td>
<td><strong>string</strong> The venue in which the game took place, such as <strong>Old Trafford</strong>. If not provided this will be blank.</td>
</tr>
<tr>
<td><code>innings</code></td>
<td><strong>integer (required)</strong> The number of the innings in which the delivery took place.</td>
</tr>
<tr>
<td><code>ball</code></td>
<td><strong>string (required)</strong> An identifier for the delivery (such as <code>23.5</code>) specifies the particular ball (in that case the 5th ball of the 24th over).</td>
</tr>
<tr>
<td><code>batting_team</code></td>
<td><strong>string (required)</strong> The name of the team which was batting for the delivery.</td>
</tr>
<tr>
<td><code>bowling_team</code></td>
<td><strong>string (required)</strong> The name of the team which was bowling for the delivery.</td>
</tr>
<tr>
<td><code>striker</code></td>
<td><strong>string (required)</strong> The name of the batter who faced the delivery.</td>
</tr>
<tr>
<td><code>non_striker</code></td>
<td><strong>string (required)</strong> The name of the non-striker during the delivery.</td>
</tr>
<tr>
<td><code>bowler</code></td>
<td><strong>string (required)</strong> The name of the bowler during the delivery.</td>
</tr>
<tr>
<td><code>runs_off_bat</code></td>
<td><strong>integer (required)</strong> The total number of runs scored by the batter off the ball. If the batter failed to score this will show <strong>0</strong></td>
</tr>
<tr>
<td><code>extras</code></td>
<td><strong>integer (required)</strong> The total number of runs conceded via extras off the ball. If no extras were conceded this will show <strong>0</strong>.</td>
</tr>
<tr>
<td><code>wides</code></td>
<td><strong>integer</strong> The number of wides conceded on the delivery. If no wides were conceded this will be blank.</td>
</tr>
<tr>
<td><code>noballs</code></td>
<td><strong>integer</strong> The number of no-balls conceded on the delivery. If no no-balls were conceded this will be blank.</td>
</tr>
<tr>
<td><code>byes</code></td>
<td><strong>integer</strong> The number of byes conceded on the delivery. If no byes were conceded this will be blank.</td>
</tr>
<tr>
<td><code>legbyes</code></td>
<td><strong>integer</strong> The number of legbyes conceded on the delivery. If no leg-byes were conceded this will be blank.</td>
</tr>
<tr>
<td><code>penalty</code></td>
<td><strong>integer</strong> The number of penalty runs conceded on the delivery. If no penalty runs were conceded this will be blank.</td>
</tr>
<tr>
<td><code>wicket_type</code></td>
<td><strong>string</strong> If a wicket fell on this delivery then this will be the kind of dismissal that took place. This will be one of <strong>bowled</strong>, <strong>caught</strong>, <strong>caught and bowled</strong>, <strong>lbw</strong>, <strong>stumped</strong>, <strong>run out</strong>, <strong>retired hurt</strong>, <strong>hit wicket</strong>, <strong>obstructing the field</strong>, <strong>hit the ball twice</strong>, <strong>handled the ball</strong>, or <strong>timed out</strong>. If no dismissals took place this will be an empty string.</td>
</tr>
<tr>
<td><code>player_dismissed</code></td>
<td><strong>string</strong> If a wicket fell on this delivery then this will be the name of the dismissed player. If no dismissals took place this will be an empty string.</td>
</tr>
<tr>
<td><code>other_wicket_type</code></td>
<td><strong>string</strong> If a second wicket occurs on the delivery (such as due to a player retiring hurt when another wicket falls) this will be the type of the dismissal, one of <strong>bowled</strong>, <strong>caught</strong>, <strong>caught and bowled</strong>, <strong>lbw</strong>, <strong>stumped</strong>, <strong>run out</strong>, <strong>retired hurt</strong>, <strong>hit wicket</strong>, <strong>obstructing the field</strong>, <strong>hit the ball twice</strong>, <strong>handled the ball</strong>, or <strong>timed out</strong>. If no dismissals took place this will be an empty string.</td>
</tr>
<tr>
<td><code>other_player_dismissed</code></td>
<td><strong>string</strong> If a second wicket fell on this delivery then this will be the name of the second dismissed player. If no dismissals took place this will be an empty string.</td>
</tr>
</tbody></table>

In [4]:
df.match_id.value_counts()

1216517    269
392190     267
1082625    263
829737     262
729315     262
          ...
392183     108
829807     106
598068     100
501265      63
1178424     51
Name: match_id, Length: 819, dtype: int64

In [17]:
df[df['penalty'].notnull()].sample(2).T

,98231,1614
match_id,729309,335988
season,2014,2007/08
start_date,2014-04-27,2008-04-22
venue,Sharjah Cricket Stadium,"Rajiv Gandhi International Stadium, Uppal"
innings,2,2
ball,4.2,11.6
batting_team,Delhi Daredevils,Delhi Daredevils
bowling_team,Mumbai Indians,Deccan Chargers
striker,M Vijay,V Sehwag
non_striker,Q de Kock,S Dhawan
bowler,SL Malinga,PP Ojha
runs_off_bat,0,0
extras,7,5
wides,2,NaN
noballs,NaN,NaN
byes,NaN,NaN
legbyes,NaN,NaN
penalty,5,5
wicket_type,NaN,NaN
player_dismissed,NaN,NaN
other_wicket_type,NaN,NaN
other_player_dismissed,NaN,NaN

In [8]:
# features = ['match_id','runs', 'wickets', 'ball', 'striker', 'non-striker']
# df = df_raw[features]
# print(df.shape)
# df.info()
venue	innings	batting_team	bowling_team	batsmen	bowlers

df.columns
['match_id', 'venue', 'innings', 'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras']

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [53]:
import os
len(os.listdir('dataset/individual_match'))

819

In [31]:
over_more_6 = (df['ball'] - df['ball'].map(np.floor)) > 0.61
df[over_more_6]

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
6,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.7,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
25,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,3.7,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,12.7,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,DJ Hussey,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,14.7,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,DJ Hussey,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,2,0.7,Royal Challengers Bangalore,Kolkata Knight Riders,W Jaffer,R Dravid,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194295,1254060,2021,2021-04-11,"MA Chidambaram Stadium, Chepauk, Chennai",2,10.7,Sunrisers Hyderabad,Kolkata Knight Riders,JM Bairstow,MK Pandey,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194296,1254060,2021,2021-04-11,"MA Chidambaram Stadium, Chepauk, Chennai",2,10.8,Sunrisers Hyderabad,Kolkata Knight Riders,JM Bairstow,MK Pandey,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194327,1254060,2021,2021-04-11,"MA Chidambaram Stadium, Chepauk, Chennai",2,15.7,Sunrisers Hyderabad,Kolkata Knight Riders,Mohammad Nabi,MK Pandey,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194328,1254060,2021,2021-04-11,"MA Chidambaram Stadium, Chepauk, Chennai",2,15.8,Sunrisers Hyderabad,Kolkata Knight Riders,Mohammad Nabi,MK Pandey,...,0,NaN,NaN,NaN,NaN,NaN,caught,Mohammad Nabi,NaN,NaN
194341,1254060,2021,2021-04-11,"MA Chidambaram Stadium, Chepauk, Chennai",2,17.7,Sunrisers Hyderabad,Kolkata Knight Riders,V Shankar,MK Pandey,...,0,NaN,NaN,NaN,NaN,NaN,caught,V Shankar,NaN,NaN

In [28]:
df[df['start_date'] == '2021-04-11'].query('ball == 18.7')

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
194221,1254060,2021,2021-04-11,"MA Chidambaram Stadium, Chepauk, Chennai",1,18.7,Kolkata Knight Riders,Sunrisers Hyderabad,KD Karthik,Shakib Al Hasan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN